import type { ChapterDefinition } from "../../../contracts/content.ts";
export default {
  bossId: "echo-archivist",
  id: "echo-gallery",
  name: "回声回廊",
  bossName: "镜页织者",
  rooms: [
    {
      id: "echo-gallery-1",
      boss: false,
      waves: 3,
      opening: ["nib", "quill", "wisp"],
      enemies: [
        "nib",
        "quill",
        "guard",
        "split",
        "scribe",
        "leech",
        "ram",
        "mortar",
        "priest",
        "mirror",
      ],
      routes: ["rest", "gift", "trial"],
    },
    {
      id: "echo-gallery-2",
      boss: false,
      waves: 3,
      opening: ["nib", "quill", "wisp"],
      enemies: [
        "nib",
        "quill",
        "guard",
        "split",
        "scribe",
        "leech",
        "ram",
        "mortar",
        "priest",
        "mirror",
      ],
      routes: ["rest", "trial", ["trade", "forge"]],
    },
    {
      id: "echo-gallery-3",
      boss: true,
      waves: 3,
      opening: ["nib", "quill", "wisp"],
      enemies: [
        "nib",
        "quill",
        "guard",
        "split",
        "wisp",
        "scribe",
        "leech",
        "sentinel",
        "ram",
        "mortar",
        "priest",
        "binder",
        "mirror",
        "brood",
        "reaper",
        "vortex",
      ],
      routes: ["rest", "trade", "shelter"],
    },
  ],
} satisfies ChapterDefinition;
