import type { ChapterDefinition } from "../../../contracts/content.ts";
export default {
  ambience: 1.5,
  bossId: "final-editor",
  id: "final-court",
  name: "终稿之庭",
  bossName: "大校对官",
  rooms: [
    {
      id: "final-court-1",
      boss: false,
      waves: 3,
      opening: ["nib", "quill", "wisp"],
      enemies: [
        "nib",
        "quill",
        "guard",
        "split",
        "wisp",
        "scribe",
        "leech",
        "sentinel",
        "ram",
        "mortar",
        "priest",
        "binder",
        "mirror",
        "brood",
        "reaper",
        "vortex",
      ],
      routes: ["rest", "gift", "trial"],
    },
    {
      id: "final-court-2",
      boss: false,
      waves: 3,
      opening: ["nib", "quill", "wisp"],
      enemies: [
        "nib",
        "quill",
        "guard",
        "split",
        "wisp",
        "scribe",
        "leech",
        "sentinel",
        "ram",
        "mortar",
        "priest",
        "binder",
        "mirror",
        "brood",
        "reaper",
        "vortex",
      ],
      routes: ["rest", "trial", ["trade", "forge"]],
    },
    {
      id: "final-court-3",
      boss: true,
      waves: 3,
      opening: ["nib", "quill", "wisp"],
      enemies: [
        "nib",
        "quill",
        "guard",
        "split",
        "wisp",
        "scribe",
        "leech",
        "sentinel",
        "ram",
        "mortar",
        "priest",
        "binder",
        "mirror",
        "brood",
        "reaper",
        "vortex",
      ],
      routes: ["rest", "trade", "shelter"],
    },
  ],
} satisfies ChapterDefinition;
