import type { AppearanceDefinition } from "../contracts/content.ts";
export const appearances = [
  { id: "nib", kind: "enemy", shape: "nib" },
  { id: "quill", kind: "enemy", shape: "quill" },
  { id: "guard", kind: "enemy", shape: "guard" },
  { id: "split", kind: "enemy", shape: "split" },
  { id: "wisp", kind: "enemy", shape: "wisp" },
  { id: "scribe", kind: "enemy", shape: "scribe" },
  { id: "leech", kind: "enemy", shape: "leech" },
  { id: "sentinel", kind: "enemy", shape: "sentinel" },
  { id: "tower", kind: "enemy", shape: "tower" },
  { id: "ram", kind: "enemy", shape: "ram" },
  { id: "mortar", kind: "enemy", shape: "mortar" },
  { id: "priest", kind: "enemy", shape: "priest" },
  { id: "binder", kind: "enemy", shape: "binder" },
  { id: "mirror", kind: "enemy", shape: "mirror" },
  { id: "brood", kind: "enemy", shape: "brood" },
  { id: "reaper", kind: "enemy", shape: "reaper" },
  { id: "vortex", kind: "enemy", shape: "vortex" },
  { id: "boss0", kind: "boss", shape: "0" },
  { id: "boss1", kind: "boss", shape: "1" },
  { id: "boss2", kind: "boss", shape: "2" },
  { id: "player-frost", kind: "player", shape: "frost" },
  { id: "player-storm", kind: "player", shape: "storm" },
  { id: "player-spirit", kind: "player", shape: "spirit" },
  { id: "rune", kind: "node", shape: "rune" },
  { id: "ink", kind: "node", shape: "ink" },
  { id: "paper-spirit", kind: "spirit", shape: "paper" },
  { id: "player-flame", kind: "player", shape: "flame" },
] as const satisfies readonly AppearanceDefinition[];
