import type { SoundCue } from '../contracts/audio.ts';
const cue = (source: string, spatial: boolean, gain: number, cooldown: number, priority = 2, group: SoundCue['group'] = 'battle', limit = spatial ? 6 : 3): SoundCue =>
  ({ source, spatial, gain, cooldown, priority, group, limit, variants: [0, 1, 2] });
// Only these references (and their selected variants) enter the release.
export const soundCues = {
  'ui.ritualRise': { ...cue('DSGNWhsh_WHOOSH NEUTRAL-Closing In_B00M_MUIDS.wav', false, .52, 1, 6, 'ui', 1), variants: [0], duration: .864 },
  'ui.ritualImpact': { ...cue('MAGPoof_POOF LARGE LIGHT-Slammer_B00M_MUIDS.wav', false, .95, 1, 7, 'ui', 1), variants: [0], offset: .465, duration: 2.35 },
  'ui.ritualChime': { ...cue('UIMisc_CONFIRM-Soft Shine_B00M_MUIDS.wav', false, .46, .5, 5, 'ui', 2), variants: [0] },
  'ui.book': { ...cue('DSGNWhsh_WHOOSH NEUTRAL-Spellbook_B00M_MUIDS.wav', false, .6, .16, 5, 'ui', 2), variants: [0, 1] },
  'ui.enter': { ...cue('UIMisc_MENU OPEN LARGE-Arrival_B00M_MUIDS.wav', false, .5, 1.5, 6, 'ui', 1), variants: [0], offset: .17 },
  'ui.type': { ...cue('UIClick_FOCUS-Clicker_B00M_MUIDS.wav', false, .24, .018, 2, 'ui', 8), duration: .11 },
  'ui.focus': cue('UIClick_FOCUS-Hover_B00M_MUIDS.wav', false, .24, .08, 1, 'ui', 2),
  'ui.select': cue('UIClick_SELECT-Choice_B00M_MUIDS.wav', false, .48, .08, 4, 'ui'),
  'ui.open': cue('UIMisc_MENU OPEN SMALL-Ancient Scroll_B00M_MUIDS.wav', false, .48, .15, 4, 'ui'),
  'ui.close': cue('UIMisc_MENU CLOSE SMALL-Ancient Scroll_B00M_MUIDS.wav', false, .42, .15, 4, 'ui'),
  'ui.confirm': cue('UIMisc_CONFIRM-Ready_B00M_MUIDS.wav', false, .55, .15, 4, 'ui'),
  'ui.invalid': cue('UIMisc_INVALID-Denial_B00M_MUIDS.wav', false, .36, .18, 3, 'ui'),
  'ui.tab': cue('UIMisc_TAB SWITCH-Pager_B00M_MUIDS.wav', false, .3, .1, 2, 'ui'),
  'key': { ...cue('UIClick_FOCUS-Clicker_B00M_MUIDS.wav', false, .28, .018, 2, 'battle', 8), duration: .11 },
  'cast.frost': cue('DSGNWhsh_WHOOSH LIGHT-Shimmer_B00M_MUIDS.wav', true, .65, .055, 2, 'frost'),
  'cast.storm': cue('MAGPoof_POOF SMALL LIGHT-Enlightenment_B00M_MUIDS.wav', true, .62, .055, 2, 'storm'),
  'cast.spirit': cue('DSGNWhsh_WHOOSH NEUTRAL-Spellbook_B00M_MUIDS.wav', true, .64, .06, 2, 'spirit'),
  'cast.flame': cue('DSGNWhsh_WHOOSH NEUTRAL-Wild Breath_B00M_MUIDS.wav', true, .68, .06, 2, 'flame'),
  'impact.frost': cue('MAGPoof_POOF SMALL LIGHT-Mystic_B00M_MUIDS.wav', true, .52, .055, 1, 'frost', 8),
  'impact.storm': cue('UIMisc_CONFIRM-Anvil_B00M_MUIDS.wav', true, .48, .055, 1, 'storm', 8),
  'impact.spirit': cue('MAGPoof_POOF LARGE NEUTRAL-Spirit Sprite_B00M_MUIDS.wav', true, .48, .06, 1, 'spirit', 8),
  'impact.flame': cue('UIMisc_CONFIRM-Ember Tap_B00M_MUIDS.wav', true, .6, .07, 1, 'flame', 8),
  'impact.blast': cue('MAGPoof_POOF LARGE NEUTRAL-Big Bang_B00M_MUIDS.wav', true, .65, .1, 2),
  'kill': cue('MAGPoof_POOF SMALL NEUTRAL-Reprieve_B00M_MUIDS.wav', true, .38, .07, 1),
  'boss.kill': cue('MAGPoof_POOF LARGE DARK-Voidthorn Curse_B00M_MUIDS.wav', true, .8, .5, 5),
  'hit': cue('MAGPoof_POOF SMALL DARK-Negate_B00M_MUIDS.wav', false, .6, .14, 5),
  'dash': cue('DSGNWhsh_WHOOSH NEUTRAL-Passby_B00M_MUIDS.wav', true, .5, .12, 4),
  'parry.activate': { ...cue('UIClick_SELECT-Choice_B00M_MUIDS.wav', true, .25, .12, 3), duration: .18 },
  'parry': cue('UIMisc_CONFIRM-Anvil_B00M_MUIDS.wav', true, .85, .1, 6),
  'parry.ring': { ...cue('UIMisc_CONFIRM-Soft Shine_B00M_MUIDS.wav', true, .5, .1, 5), duration: .8 },
  'perfect': cue('MAGSpel_POTION MANA-Rejuvenate_B00M_MUIDS.wav', false, .5, .25, 4),
  'overload': cue('MAGPoof_POOF LARGE LIGHT-Slammer_B00M_MUIDS.wav', true, .7, .12, 3, 'storm'),
  'ready': cue('UIMisc_NOTIFICATION-Rune Ping_B00M_MUIDS.wav', false, .55, .4, 5),
  'charge': cue('DSGNWhsh_WHOOSH NEUTRAL-Closing In_B00M_MUIDS.wav', true, .6, .15, 4),
  'laser': cue('DSGNWhsh_WHOOSH LIGHT-Enchanted Whisp_B00M_MUIDS.wav', true, .62, .12, 4),
  'ultimate.frost': cue('MAGPoof_POOF LARGE LIGHT-Secret Loot_B00M_MUIDS.wav', true, .85, .6, 6, 'frost'),
  'ultimate.storm': cue('MAGPoof_POOF LARGE LIGHT-Slammer_B00M_MUIDS.wav', true, .85, .6, 6, 'storm'),
  'ultimate.spirit': cue('MAGPoof_POOF LARGE NEUTRAL-Phantom Whisper_B00M_MUIDS.wav', true, .85, .6, 6, 'spirit'),
  'ultimate.flame': cue('MAGPoof_POOF LARGE DARK-Grapeshot_B00M_MUIDS.wav', true, .85, .6, 6, 'flame'),
  'reward': cue('UIMisc_REWARD MAGIC-Gem Stone_B00M_MUIDS.wav', false, .6, .2, 4),
  'level': cue('MAGPoof_LEVEL UP-Ascend_B00M_MUIDS.wav', false, .65, .4, 5),
  'pickup': cue('MAGSpel_POTION HEALTH-Refresh_B00M_MUIDS.wav', true, .5, .12, 3),
  'chapter': cue('MAGMisc_QUEST CHECKPOINT-Waystone_B00M_MUIDS.wav', false, .65, .4, 5),
  'victory': cue('UIMisc_QUEST COMPLETE-Complete_B00M_MUIDS.wav', false, .7, 1, 6),
  'defeat': cue('UIMisc_QUEST FAIL-Reprise_B00M_MUIDS.wav', false, .65, 1, 6),
} as const satisfies Record<string, SoundCue>;
export type SoundCueId = keyof typeof soundCues;

