"""Compress complete local fonts; run only when the source fonts change."""
from concurrent.futures import ThreadPoolExecutor
from hashlib import sha256
from pathlib import Path
import json
from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parents[1]
FONTS = [
    ('汇文明朝体', '汇文明朝体.ttf', 'huiwen-ming.woff2'),
    ('京華老宋体v3.0', '京華老宋体v3.0.ttf', 'jinghua-song.woff2'),
]

def build(item):
    family, source_name, output_name = item
    source = ROOT / 'public/font' / source_name
    output = ROOT / 'public/font' / output_name
    font = TTFont(source, recalcTimestamp=False)
    cmap = font.getBestCmap()
    glyphs = font['maxp'].numGlyphs
    font.flavor = 'woff2'
    font.save(output)
    packed = TTFont(output)
    assert packed.getBestCmap() == cmap and packed['maxp'].numGlyphs == glyphs
    digest = sha256(output.read_bytes()).hexdigest()
    print(f'{family}: {source.stat().st_size:,} -> {output.stat().st_size:,} bytes; {glyphs:,} glyphs retained', flush=True)
    return {
        'family': family, 'source': f'public/font/{source_name}',
        'sourceSha256': sha256(source.read_bytes()).hexdigest(),
        'file': f'font/{output_name}', 'bytes': output.stat().st_size,
        'sha256': digest, 'glyphs': glyphs,
    }

with ThreadPoolExecutor(max_workers=2) as pool:
    fonts = list(pool.map(build, FONTS))
(ROOT/'data/font-build.json').write_text(json.dumps(fonts, ensure_ascii=False, indent=2)+'\n', encoding='utf-8')
manifest = [{'family':f['family'], 'url':f"./{f['file']}?v={f['sha256'][:12]}", 'bytes':f['bytes']} for f in fonts]
(ROOT/'src/generated/font-manifest.ts').write_text('// Generated by tools/fonts.py; complete WOFF2 fonts, no glyph subsetting.\nexport const gameFonts = '+json.dumps(manifest,ensure_ascii=False,indent=2)+' as const;\n',encoding='utf-8')
